name: Build and Release Flatpak

on:
  push:
    tags:
      - "v*"  # Triggert nur bei Versionstags wie v1.0, v1.1 etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Flatpak and Flatpak Builder
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder

      - name: Add Flathub Remote (User Mode)
        run: |
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak --user update -y

      - name: Install required Flatpak SDKs
        run: |
          flatpak --user install -y flathub org.freedesktop.Sdk//23.08
          flatpak --user install -y flathub org.freedesktop.Platform//23.08

      - name: Build Flatpak (User Mode)
        run: |
          flatpak-builder --user --repo=repo build-dir de.kidslab.mcreator.yml --force-clean

      - name: Export as Bundle
        run: |
          flatpak build-bundle repo de.kidslab.mcreator.flatpak de.kidslab.mcreator --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo

      - name: Upload Flatpak Bundle as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: de.kidslab.mcreator
          path: de.kidslab.mcreator.flatpak

      - name: Upload to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: de.kidslab.mcreator.flatpak
